services:
  cometbft-node0:
    image: dews-image:latest
    container_name: cometbft-node0
    ports:
      - "5000:5000"
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./node-config/node0:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5000"
    networks:
      - dews-network

  cometbft-node1:
    image: dews-image:latest
    container_name: cometbft-node1
    ports:
      - "5001:5001"
      - "9002:9002"
      - "9003:9003"
    volumes:
      - ./node-config/node1:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5001"
    networks:
      - dews-network

  cometbft-node2:
    image: dews-image:latest
    container_name: cometbft-node2
    ports:
      - "5002:5002"
      - "9004:9004"
      - "9005:9005"
    volumes:
      - ./node-config/node2:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5002"
    networks:
      - dews-network

  cometbft-node3:
    image: dews-image:latest
    container_name: cometbft-node3
    ports:
      - "5003:5003"
      - "9006:9006"
      - "9007:9007"
    volumes:
      - ./node-config/node3:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5003"
    networks:
      - dews-network

  cometbft-node4:
    image: dews-image:latest
    container_name: cometbft-node4
    ports:
      - "5004:5004"
      - "9008:9008"
      - "9009:9009"
    volumes:
      - ./node-config/node4:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5004"
    networks:
      - dews-network

  cometbft-node5:
    image: dews-image:latest
    container_name: cometbft-node5
    ports:
      - "5005:5005"
      - "9010:9010"
      - "9011:9011"
    volumes:
      - ./node-config/node5:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5005"
    networks:
      - dews-network

  cometbft-node6:
    image: dews-image:latest
    container_name: cometbft-node6
    ports:
      - "5006:5006"
      - "9012:9012"
      - "9013:9013"
    volumes:
      - ./node-config/node6:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5006"
    networks:
      - dews-network

  cometbft-node7:
    image: dews-image:latest
    container_name: cometbft-node7
    ports:
      - "5007:5007"
      - "9014:9014"
      - "9015:9015"
    volumes:
      - ./node-config/node7:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5007"
    networks:
      - dews-network

  cometbft-node8:
    image: dews-image:latest
    container_name: cometbft-node8
    ports:
      - "5008:5008"
      - "9016:9016"
      - "9017:9017"
    volumes:
      - ./node-config/node8:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5008"
    networks:
      - dews-network

  cometbft-node9:
    image: dews-image:latest
    container_name: cometbft-node9
    ports:
      - "5009:5009"
      - "9018:9018"
      - "9019:9019"
    volumes:
      - ./node-config/node9:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5009"
    networks:
      - dews-network

networks:
  dews-network:
    driver: bridge
