services:
  cometbft-node0:
    image: dews-image:latest
    container_name: cometbft-node0
    ports:
      - "5000:5000"
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./node-config/node0:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5000"
    networks:
      - dews-network

networks:
  dews-network:
    driver: bridge
