services:
  cometbft-node0:
    image: dews-image:latest
    container_name: cometbft-node0
    ports:
      - "5000:5000"
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./node-config/node0:/root/.cometbft
    command: >
      sh -c "/app/bin --cmt-home=/root/.cometbft --http-port 5000 --postgres-host=postgres-node0:5432"
    networks:
      - dews-network
  postgres-node0:
    image: postgres:14
    container_name: postgres-node0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: dewsdb
    volumes:
      - postgres-data-node0:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dews-network

networks:
  dews-network:
    driver: bridge

volumes:
  postgres-data-node0:
